package net.darkhax.haunted;

import java.util.Arrays;

import net.darkhax.haunted.blocks.HauntedBlocks;
import net.darkhax.haunted.entitys.HauntedEntitys;
import net.darkhax.haunted.handler.RenderingHandler;
import net.darkhax.haunted.items.HauntedItems;
import net.darkhax.haunted.proxys.CommonProxy;
import net.darkhax.haunted.util.Constants;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraftforge.common.MinecraftForge;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(name = Constants.NAME, modid = Constants.MODID, version = Constants.VERSION)
public class Haunted {
    
    public static CreativeTabs tabsHaunted = new CreativeTabHaunted();
    
    @Mod.Instance(Constants.MODID)
    public static Haunted instance;
    
    @SidedProxy(clientSide = Constants.CLIENT, serverSide = Constants.COMMON)
    public static CommonProxy proxy;
    
    @Mod.EventHandler
    public void preInit (FMLPreInitializationEvent event) {
    
        setModInfo(event.getModMetadata());
        new HauntedBlocks();
        new HauntedItems();
        new HauntedEntitys();
        proxy.registerRenders();
        proxy.registerSidedEvents();
        MinecraftForge.EVENT_BUS.register(new RenderingHandler());
    }
    
    @Mod.EventHandler
    public void init (FMLInitializationEvent event) {
    
    }
    
    @Mod.EventHandler
    public void postInit (FMLPostInitializationEvent event) {
    
    }
    
    /**
     * Method used to provide information on the mod. This is the code equivalent of a
     * mcmod.info file.
     * 
     * @param meta: An instance of the ModMetadata.
     */
    void setModInfo (ModMetadata meta) {
    
        meta.authorList = Arrays.asList(new String[] { "Crowfick", "Darkhax", "HoopAWolf" });
        meta.logoFile = "";
        meta.credits = "";
        meta.description = "";
        meta.url = "";
        meta.autogenerated = false;
    }
}